### ISSUE TITLE
error when pip3 install

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-webclient-pack#13]
Hi

When i do : sudo python3 -m pip install gns3-webclient-pack
I have this error message : 

```

Collecting gns3-webclient-pack
  Downloading https://files.pythonhosted.org/packages/db/53/d6bea14d874ba7cf44980512ef5855759ada3f3da5a6d7b19ebe13488ba4/gns3-webclient-pack-1.0.0b2.tar.gz (188kB)
    100% |████████████████████████████████| 194kB 2.7MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-doqbclll/gns3-webclient-pack/setup.py", line 35, in <module>
        install_requires=open("requirements.txt", "r").read().splitlines(),
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-doqbclll/gns3-webclient-pack
```

**Comment by grossmj** [comment]
The latest version wasn't uploaded correctly. Thanks for catching that. This should work now: https://pypi.org/project/gns3-webclient-pack/
