### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [GNS3/gns3-webclient-pack#9]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.0.0b2. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary gns3-webclient-pack -w /tmp/ext gns3-webclient-pack==1.0.0b2
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting gns3-webclient-pack==1.0.0b2
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/2d1/b752c77176d4f/gns3-webclient-pack-1.0.0b2.tar.gz (188 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-gv6wj665/gns3-webclient-pack/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-gv6wj665/gns3-webclient-pack/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-gv6wj665/gns3-webclient-pack/pip-egg-info
         cwd: /tmp/pip-wheel-gv6wj665/gns3-webclient-pack/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-gv6wj665/gns3-webclient-pack/setup.py", line 35, in <module>
        install_requires=open("requirements.txt", "r").read().splitlines(),
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by grossmj** [comment]
Thanks this should be fixed now :+1:  We will release a new version soon.
